-- CreateTable
CREATE TABLE "FxSettings" (
    "id" INTEGER NOT NULL DEFAULT 1,
    "debrisCount" INTEGER NOT NULL DEFAULT 320,
    "wardenCount" INTEGER NOT NULL DEFAULT 5,
    "split" DOUBLE PRECISION NOT NULL DEFAULT 0.4,
    "chaos" DOUBLE PRECISION NOT NULL DEFAULT 0.5,
    "drift" DOUBLE PRECISION NOT NULL DEFAULT 0.38,
    "lurk" DOUBLE PRECISION NOT NULL DEFAULT 0.45,
    "bgBright" DOUBLE PRECISION NOT NULL DEFAULT 0.5,
    "bgSat" DOUBLE PRECISION NOT NULL DEFAULT 0.5,
    "bgContrast" DOUBLE PRECISION NOT NULL DEFAULT 0.5,
    "staticAmt" DOUBLE PRECISION NOT NULL DEFAULT 0.18,
    "staticSpeed" DOUBLE PRECISION NOT NULL DEFAULT 0.55,
    "vignette" DOUBLE PRECISION NOT NULL DEFAULT 0.5,
    "caInitial" DOUBLE PRECISION NOT NULL DEFAULT 0.15,
    "caBurst" DOUBLE PRECISION NOT NULL DEFAULT 0.6,
    "wardenHue" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "trailAmt" DOUBLE PRECISION NOT NULL DEFAULT 0.4,
    "wardenReveal" DOUBLE PRECISION NOT NULL DEFAULT 0.65,
    "wardenHuskBright" DOUBLE PRECISION NOT NULL DEFAULT 0.3,
    "wardenOrbBright" DOUBLE PRECISION NOT NULL DEFAULT 0.3,
    "glowHue" DOUBLE PRECISION NOT NULL DEFAULT 280,
    "glowSat" DOUBLE PRECISION NOT NULL DEFAULT 0.6,
    "glowBright" DOUBLE PRECISION NOT NULL DEFAULT 0.45,

    CONSTRAINT "FxSettings_pkey" PRIMARY KEY ("id")
);
