import assert from "node:assert/strict";
import { cleanKind, pollTally, optionCountOf, isMediaUrl, mmss } from "../src/lib/chatKinds.ts";
assert.equal(cleanKind("evil", {}).ok, false);
const cq = cleanKind("cq", { topic: " ice drones ", wants: ["feedback", "x", "feedback", "collab"] });
assert.ok(cq.ok && cq.text === "[CQ] ice drones (looking for: feedback, collab)");
assert.equal(cleanKind("cq", { topic: " " }).ok, false);
const rp = cleanKind("report", { target: "https://x.y/z", r: 5, s: 7, t: "6", note: "warm" });
assert.ok(rp.ok && rp.text === "[Report] https://x.y/z: R5 S7 T6 - warm");
assert.equal(cleanKind("report", { target: "a", r: 6, s: 7, t: 7 }).ok, false);
assert.equal(cleanKind("report", { target: "a", r: 3, s: 0, t: 7 }).ok, false);
assert.equal(cleanKind("poll", { q: "q", options: ["a"] }).ok, false);
const pl = cleanKind("poll", { q: "Which?", options: ["a", " ", "b", "c", "d", "e", "f", "g"] });
assert.ok(pl.ok && (pl.data.options as string[]).length === 6 && pl.text.startsWith("[Poll] Which?\n1) a\n2) b"));
assert.equal(cleanKind("ab", { q: "q", a: "https://a/x.mp3", b: "javascript:alert(1)" }).ok, false);
assert.equal(cleanKind("ab", { q: "q", a: "/uploads/a.mp3", b: "https://b/x.mp3" }).ok, true);
assert.equal(isMediaUrl("//evil.com/x"), false); assert.equal(isMediaUrl("http://plain/x"), false);
const c = cleanKind("clip", { url: "https://a/b.mp3", from: 12.4, to: 20.2, label: "the swell" });
assert.ok(c.ok && c.data.from === 12 && c.data.to === 21 && c.text === "[Clip] the swell 0:12-0:20 https://a/b.mp3");
assert.equal(cleanKind("clip", { url: "https://a/b.mp3", from: 10, to: 5 }).ok, false);
assert.equal(cleanKind("clip", { url: "https://a/b.mp3", from: 0, to: 500 }).ok, false);
assert.deepEqual(pollTally(3, [0, 0, 2, 5, -1, 1.5]), { counts: [2, 0, 1], total: 3 });
assert.equal(optionCountOf("ab", {}), 2); assert.equal(optionCountOf("poll", { options: [1, 2, 3] }), 3); assert.equal(optionCountOf("text", {}), 0);
assert.equal(mmss(75), "1:15");
console.log("chatKinds ok");
