import assert from "node:assert/strict";
import { canHaveFile, couponProblem, generateCode, imagesInMarkdown, isValidCode, makeLimiter, normalizeCode } from "../src/lib/resourceAccess.ts";

const ok = (name: string) => console.log("ok  ", name);
assert.equal(normalizeCode("  ab cd-12 "), "ABCD-12"); ok("codes ignore case and spaces");
assert.equal(normalizeCode(5), ""); ok("non-text is empty");
assert.ok(isValidCode("ABCDE-23456")); assert.ok(!isValidCode("ab")); assert.ok(!isValidCode("A B")); ok("code shape");
const g = generateCode(); assert.match(g, /^[A-HJ-KM-NP-Z2-9]{5}-[A-HJ-KM-NP-Z2-9]{5}$/); assert.ok(isValidCode(g)); ok("generated code is readable");
assert.notEqual(generateCode(), generateCode()); ok("codes differ");
const base = { active: true, itemId: null, maxUses: null, uses: 0, expiresAt: null };
assert.equal(couponProblem(base, 3), null); ok("open coupon works");
assert.match(couponProblem({ ...base, active: false }, 3)!, /switched off/); ok("inactive");
assert.match(couponProblem({ ...base, itemId: 4 }, 3)!, /different resource/); ok("other resource");
assert.equal(couponProblem({ ...base, itemId: 3 }, 3), null); ok("right resource");
assert.match(couponProblem({ ...base, expiresAt: new Date(1000) }, 3, new Date(2000))!, /expired/); ok("expired");
assert.equal(couponProblem({ ...base, expiresAt: new Date(3000) }, 3, new Date(2000)), null); ok("not yet expired");
assert.match(couponProblem({ ...base, maxUses: 2, uses: 2 }, 3)!, /used up/); ok("used up");
assert.equal(couponProblem({ ...base, maxUses: 2, uses: 1 }, 3), null); ok("one use left");
const paid = { paid: true, ownerId: 7 };
assert.ok(canHaveFile({ paid: false, ownerId: 7 }, null, false)); ok("free for everyone");
assert.ok(!canHaveFile(paid, null, false)); ok("paid: visitor locked");
assert.ok(!canHaveFile(paid, { id: 1, isAdmin: false }, false)); ok("paid: member locked");
assert.ok(canHaveFile(paid, { id: 1, isAdmin: false }, true)); ok("paid: unlocked member");
assert.ok(canHaveFile(paid, { id: 7, isAdmin: false }, false)); ok("paid: owner");
assert.ok(canHaveFile(paid, { id: 1, isAdmin: true }, false)); ok("paid: admin");
let t = 0; const lim = makeLimiter(3, 1000, () => t);
assert.ok(lim.hit("a") && lim.hit("a") && lim.hit("a")); assert.ok(!lim.hit("a")); assert.ok(lim.hit("b")); ok("limiter blocks the 4th try");
t = 1500; assert.ok(lim.hit("a")); ok("limiter forgets");
assert.deepEqual(imagesInMarkdown("a ![x](/uploads/a.png) b ![y](https://e.com/b.jpg \"t\") ![x](/uploads/a.png) ![z](javascript:alert(1)){w=50}"), ["/uploads/a.png", "https://e.com/b.jpg"]); ok("pictures in a text");
