import assert from "node:assert/strict";
import { parseSlash, hintFor } from "../src/lib/chatCommands.ts";
import { audible } from "../src/lib/squelch.ts";
const ok = (r: ReturnType<typeof parseSlash>) => { assert.ok(r && r.ok); return (r as { ok: true; msg: { kind: string; data: any } }).msg; };
assert.equal(parseSlash("hello"), null); assert.equal(parseSlash("/etc/hosts is a file"), null); assert.equal(parseSlash("/unknown thing"), null);
let m = ok(parseSlash("/cq ice drones +feedback +collab please"));
assert.equal(m.kind, "cq"); assert.equal(m.data.topic, "ice drones please"); assert.deepEqual(m.data.wants, ["feedback", "collab"]);
m = ok(parseSlash("/report https://x.y/a.mp3 5/7/6 warm low end"));
assert.deepEqual([m.data.target, m.data.r, m.data.s, m.data.t, m.data.note], ["https://x.y/a.mp3", 5, 7, 6, "warm low end"]);
m = ok(parseSlash("/report my cave recording 579"));
assert.deepEqual([m.data.target, m.data.r, m.data.s, m.data.t], ["my cave recording", 5, 7, 9]);
assert.equal(parseSlash("/report https://x 9/9/9")!.ok, false);
m = ok(parseSlash("/poll Which? | a | b | c")); assert.deepEqual(m.data.options, ["a", "b", "c"]);
assert.equal(parseSlash("/poll Which? | a")!.ok, false);
m = ok(parseSlash("/ab Warmer? | https://a/1.mp3 | https://a/2.mp3")); assert.equal(m.data.b, "https://a/2.mp3");
m = ok(parseSlash("/clip https://a/x.mp3 1:05-1:20 the swell")); assert.deepEqual([m.data.from, m.data.to, m.data.label], [65, 80, "the swell"]);
m = ok(parseSlash("/clip /uploads/x.wav 3-9")); assert.deepEqual([m.data.from, m.data.to, m.data.label], [3, 9, ""]);
assert.equal(parseSlash("/clip https://a/x.mp3")!.ok, false); assert.equal(parseSlash("/cq")!.ok, false);
const help = parseSlash("/help"); assert.ok(help && !help.ok && help.error.includes("/poll"));
assert.deepEqual(hintFor("/").map((c) => c.verb), ["cq", "report", "poll", "ab", "clip"]); assert.deepEqual(hintFor("/p").map((c) => c.verb), ["poll"]);
assert.deepEqual(hintFor("/poll Which").map((c) => c.verb), ["poll"]); assert.equal(hintFor("hello").length, 0);
const msg = (o: any) => ({ id: 1, authorId: 2, authorUsername: "bob", contentRaw: "hi", attachments: [], embeds: [], isDeleted: false, replyToId: null, replyPreview: null, kind: "text", ...o });
const me = { id: 1, username: "tachy" };
assert.equal(audible(msg({}), 0, me), true); assert.equal(audible(msg({}), 1, me), false);
assert.equal(audible(msg({ contentRaw: "this is a longer thought" }), 1, me), true); assert.equal(audible(msg({ contentRaw: "this is a longer thought" }), 2, me), false);
assert.equal(audible(msg({ contentRaw: "see https://a.b/c" }), 2, me), true); assert.equal(audible(msg({ contentRaw: "lol @tachy" }), 2, me), true);
assert.equal(audible(msg({ kind: "poll" }), 3, me), true); assert.equal(audible(msg({ contentRaw: "see https://a.b/c" }), 3, me), false);
assert.equal(audible(msg({ authorId: 1 }), 3, me), true); assert.equal(audible(msg({ replyPreview: { authorUsername: "tachy" } }), 2, me), true);
console.log("chat ok");
