import assert from "node:assert/strict";
import { buildTree, visibleRows } from "../src/lib/logTree.ts";
const ok = (n: string) => console.log("ok  ", n);
const nodes = buildTree([{ id: 1, slug: "a", title: "Alpha", parentId: null }]);
const posts = [{ id: 1, slug: "p", title: "First post", publishedAt: "2026-01-01" }];
const studies = Array.from({ length: 12 }, (_, i) => ({ slug: `s${i}`, title: `Study ${i}`, owner: i === 3 ? "ana" : "bo" }));
const base = { nodes, posts, open: new Set<number>(), newsOpen: false, query: "" };
let rows = visibleRows({ ...base, studies });
assert.deepEqual(rows.map((r) => r.kind), ["news-folder", "page", "studies"]); ok("studies folder is closed by default");
assert.equal(rows.at(-1)!.hasChildren, true); ok("it can open");
rows = visibleRows({ ...base, studies, studiesOpen: true });
assert.equal(rows.filter((r) => r.kind === "study").length, 8); assert.equal(rows.find((r) => r.kind === "study")!.to, "/study/s0"); ok("an open folder lists the latest eight, linking to the study");
rows = visibleRows({ ...base, studies, query: "ana" });
assert.deepEqual(rows.filter((r) => r.kind === "study").map((r) => r.label), ["Study 3"]); ok("search finds a study by its owner and opens the folder");
rows = visibleRows({ ...base, studies, query: "study 11" });
assert.equal(rows.filter((r) => r.kind === "study").length, 1); ok("search reaches studies beyond the first eight");
rows = visibleRows({ ...base, query: "alpha" });
assert.deepEqual(rows.map((r) => r.kind), ["page"]); ok("an unrelated search hides the folders");
rows = visibleRows(base);
assert.equal(rows.at(-1)!.hasChildren, false); ok("no studies loaded: still a link");
