import { touchRecent, pin, unpin, slotOf, freeSlot, dialOrder, tune, toggleSleep, saveScene, removeScene, heat, fromRemote, SLOTS, MAX_RECENTS } from "../src/lib/rooms";
let n = 0; const ok = (c: boolean, m: string) => { if (!c) { console.log("FAIL", m); process.exitCode = 1; } else { n++; console.log("ok  ", m); } };
const R = (s: string) => ({ slug: s, name: s.toUpperCase() });
let rec = touchRecent([], R("a")); rec = touchRecent(rec, R("b")); rec = touchRecent(rec, R("a"));
ok(rec.map((r) => r.slug).join() === "a,b", "recent: most recent first, no duplicates");
let r = [] as any[]; for (let i = 0; i < 12; i++) r = touchRecent(r, R("x" + i)); ok(r.length === MAX_RECENTS && r[0].slug === "x11", "recent: capped");
let s: any[] = pin([], 2, R("a")); ok(s.length === SLOTS && s[2].slug === "a" && s[0] === null, "pin fills a fixed slot");
s = pin(s, 4, R("a")); ok(s[2] === null && s[4].slug === "a", "pinning again moves it");
ok(slotOf(s, R("a")) === 4 && slotOf(s, R("z")) === -1 && slotOf(s, null) === -1, "slotOf");
ok(freeSlot(s) === 0 && freeSlot(Array(SLOTS).fill(R("q"))) === -1, "free slot");
s = unpin(s, 4); ok(s.every((x: any) => x === null), "unpin");
ok(pin([], 9, R("a")).length === 0, "out of range does nothing");
const order = dialOrder(pin(pin([], 1, R("b")), 0, R("a")), [R("c"), R("b"), R("d")]);
ok(order.map((o) => o.slug).join() === "a,b,c,d", "dial order: pinned by slot, then unpinned recents");
ok(tune(order, "a", 1)!.slug === "b" && tune(order, "d", 1)!.slug === "a" && tune(order, "a", -1)!.slug === "d", "tune wraps both ways");
ok(tune(order, "zzz", 1)!.slug === "a", "tune from an unknown room goes to the first");
ok(tune([R("a")], "a", 1) === null && tune([], "a", 1) === null, "nowhere to go");
ok(tune([R("a")], "other", 1)!.slug === "a", "one room, you are elsewhere: go there");
const sl = toggleSleep(pin(pin([], 0, R("a")), 1, R("b")), 1);
ok(sl[1]!.asleep === true && !sl[0]!.asleep, "a slot can sleep");
ok(tune(dialOrder(sl, [R("c")]), "a", 1)!.slug === "c", "tuning steps over a sleeping room");
ok(tune(dialOrder(sl, []), "b", 1)!.slug === "a", "but you can still be in one");
ok(toggleSleep(sl, 1)[1]!.asleep === undefined, "waking clears the flag");
let sc = saveScene([], "  Lab   night ", pin([], 0, R("a"))); ok(sc.length === 1 && sc[0].name === "Lab night" && sc[0].slots.length === SLOTS, "scene saved with a tidy name");
ok(saveScene(sc, "lab NIGHT", pin([], 2, R("z"))).length === 1 && saveScene(sc, "lab NIGHT", pin([], 2, R("z")))[0].slots[2]!.slug === "z", "same name replaces");
ok(saveScene(sc, "x", [null, null, null, null, null, null]).length === 1, "an empty dial is not a scene");
let many = [] as any[]; for (let i = 0; i < 8; i++) many = saveScene(many, "s" + i, pin([], 0, R("a"))); ok(many.length === 5 && many[0].name === "s7", "at most 5, newest first");
ok(removeScene(many, "s7").length === 4, "remove scene");
ok(heat(0) === 0 && heat(2) === 1 && heat(5) === 2 && heat(40) === 3, "heat levels");
ok(fromRemote(null) === null && fromRemote({ presets: [{ slug: "a", name: "A" }, 5], scenes: [{ name: "q", slots: [] }, 3] })!.scenes.length === 1, "remote shape guarded");
console.log(n, "passed");
