import assert from "node:assert/strict";
const store: Record<string, string> = {};
(globalThis as any).localStorage = { getItem: (k: string) => store[k] ?? null, setItem: (k: string, v: string) => { store[k] = v; } };
const { txLabel, sortNodes, filterNodes, counts, defaultTab, cleanAttempt, getSeen, markSeen, getTried, addTried, clearTried } = await import("../src/lib/signalUi.ts");
assert.equal(txLabel(7), "TX-007"); assert.equal(txLabel(1234), "TX-1234");
const N = (id: number, solved: boolean) => ({ id, solved, hasAnswer: true });
const nodes = [N(3, true), N(1, false), N(2, true), N(4, false)];
assert.deepEqual(sortNodes(nodes).map((n) => n.id), [1, 4, 2, 3]);
assert.deepEqual(filterNodes(nodes, "todo").map((n) => n.id), [1, 4]); assert.deepEqual(filterNodes(nodes, "done").map((n) => n.id), [3, 2]); assert.equal(filterNodes(nodes, "all").length, 4);
assert.deepEqual(counts(nodes), { todo: 2, done: 2 });
assert.equal(defaultTab(nodes), "todo"); assert.equal(defaultTab([N(1, true)]), "all"); assert.equal(defaultTab([]), "all");
assert.equal(cleanAttempt("  a \n  b  "), "a b"); assert.equal(cleanAttempt("x".repeat(100)).length, 60);
assert.deepEqual(getSeen(), []); markSeen([1, 2]); markSeen([2, 3]); assert.deepEqual(getSeen(), [1, 2, 3]);
assert.deepEqual(getTried(5), []); addTried(5, "Fox"); addTried(5, "dog"); addTried(5, "FOX");
assert.deepEqual(getTried(5), ["FOX", "dog"], "newest first, no case-insensitive repeats");
for (let i = 0; i < 10; i++) addTried(5, "w" + i); assert.equal(getTried(5).length, 6);
addTried(5, "   "); assert.equal(getTried(5).length, 6, "blank is not an attempt");
assert.deepEqual(getTried(6), []); clearTried(5); assert.deepEqual(getTried(5), []);
store["exomusica_signal_seen"] = "garbage"; assert.deepEqual(getSeen(), []);
console.log("signalUi: ok");
