-- AlterTable
ALTER TABLE "SiteSettings" ADD COLUMN     "forumMapInitialX" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "forumMapInitialY" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "forumMapInitialZoom" DOUBLE PRECISION NOT NULL DEFAULT 1;
